plugins {
    id 'application'
    id 'com.gradleup.shadow' version '8.3.5'
}

repositories { mavenCentral() }

dependencies {
    implementation 'org.boofcv:boofcv-all:1.1.7'
}

application { mainClass = 'org.rustqr.competitor.BoofcvDecode' }

tasks.shadowJar {
    archiveFileName = 'boofcv_decode.jar'
    manifest { attributes 'Main-Class': application.mainClass.get() }
}
