#!/usr/bin/env python3
"""Offline threshold tuning for RustQR Phase 6.

Sweeps a small grid of decode-group confidence thresholds and top-K limits,
executes reading-rate runs, enforces runtime guardrails against a baseline
artifact, and writes the best passing profile to disk.
"""

from __future__ import annotations

import argparse
import itertools
import json
import os
import subprocess
import sys
from pathlib import Path


def run_cmd(cmd: list[str], env: dict[str, str]) -> int:
    proc = subprocess.run(cmd, env=env)
    return proc.returncode


def load_artifact(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def metric_summary(path: Path) -> tuple[float, float]:
    data = load_artifact(path)
    weighted = float(data["summary"]["weighted_global_rate_percent"])
    median = float(data["summary"]["runtime"]["median_per_image_ms"])
    return weighted, median


def write_profile(path: Path, best_env: dict[str, str], best_artifact: Path) -> None:
    lines = [
        "# RustQR Phase 6 tuned profile",
        "# Generated by scripts/tune_phase6_thresholds.py",
        f"# Best artifact: {best_artifact}",
    ]
    for key in sorted(best_env):
        lines.append(f"{key}={best_env[key]}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Tune Phase 6 thresholds")
    parser.add_argument(
        "--dataset-root",
        default="benches/images/boofcv",
        help="Dataset root for reading-rate runs",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Per-category image limit (0 means full dataset)",
    )
    parser.add_argument(
        "--baseline-artifact",
        required=True,
        help="Baseline artifact JSON path used for guardrails",
    )
    parser.add_argument(
        "--out-profile",
        default="docs/phase6_tuned_profile.env",
        help="Output tuned profile file",
    )
    parser.add_argument(
        "--out-dir",
        default="target/phase6_tuning",
        help="Directory for candidate artifacts",
    )
    parser.add_argument(
        "--max-rate-drop-pp",
        type=float,
        default=1.0,
        help="Maximum allowed weighted-global drop (pp)",
    )
    parser.add_argument(
        "--max-median-runtime-regression-pct",
        type=float,
        default=15.0,
        help="Maximum allowed median runtime regression (%)",
    )
    args = parser.parse_args()

    baseline = Path(args.baseline_artifact)
    if not baseline.exists():
        print(f"Baseline artifact not found: {baseline}", file=sys.stderr)
        return 2

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    base_env = os.environ.copy()
    base_env["QR_DATASET_ROOT"] = args.dataset_root
    if args.limit >= 0:
        base_env["QR_BENCH_LIMIT"] = str(args.limit)

    top_k_values = [4, 6, 8]
    high_values = [0.72, 0.80, 0.88]
    low_values = [0.55, 0.62, 0.70]
    floor_values = [0.70, 0.78, 0.86]

    best_score = None
    best_env = None
    best_artifact = None

    combos = list(itertools.product(top_k_values, high_values, low_values, floor_values))
    for i, (top_k, high, low, floor) in enumerate(combos, start=1):
        if low >= high:
            continue

        env = base_env.copy()
        env["QR_DECODE_TOP_K"] = str(top_k)
        env["QR_GROUP_HIGH_CONF"] = f"{high:.2f}"
        env["QR_GROUP_LOW_TOP_CONF"] = f"{low:.2f}"
        env["QR_SINGLE_QR_CONF_FLOOR"] = f"{floor:.2f}"

        artifact = out_dir / f"candidate_{i:03d}.json"
        cmd = [
            "cargo",
            "run",
            "--features",
            "tools",
            "--bin",
            "qrtool",
            "--release",
            "--",
            "reading-rate",
            "--non-interactive",
            "--artifact-json",
            str(artifact),
        ]
        print(f"[{i}/{len(combos)}] Running top_k={top_k} high={high:.2f} low={low:.2f} floor={floor:.2f}")
        if run_cmd(cmd, env) != 0:
            print("  run failed, skipping")
            continue

        gate_cmd = [
            "python3",
            "scripts/compare_reading_rate_artifacts.py",
            "--baseline",
            str(baseline),
            "--candidate",
            str(artifact),
            "--max-rate-drop-pp",
            str(args.max_rate_drop_pp),
            "--max-median-runtime-regression-pct",
            str(args.max_median_runtime_regression_pct),
        ]
        gate_rc = run_cmd(gate_cmd, env)
        if gate_rc != 0:
            print("  rejected by guardrails")
            continue

        weighted, median = metric_summary(artifact)
        score = (weighted, -median)
        print(f"  accepted: weighted={weighted:.4f}% median={median:.2f} ms")

        if best_score is None or score > best_score:
            best_score = score
            best_env = {
                "QR_DECODE_TOP_K": str(top_k),
                "QR_GROUP_HIGH_CONF": f"{high:.2f}",
                "QR_GROUP_LOW_TOP_CONF": f"{low:.2f}",
                "QR_SINGLE_QR_CONF_FLOOR": f"{floor:.2f}",
            }
            best_artifact = artifact

    if best_env is None or best_artifact is None:
        print("No candidate passed guardrails", file=sys.stderr)
        return 1

    out_profile = Path(args.out_profile)
    write_profile(out_profile, best_env, best_artifact)
    print(f"Best profile written to {out_profile}")
    print(f"Best artifact: {best_artifact}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

